apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mlflow.fullname" . }}-db-migrate
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mlflow-db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - mlflow
        - db
        - upgrade
        - "sqlite:///data/mlflow.db"
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://rustfs-svc:9000"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "mlflow.fullname" . }}-data
